// 06-svelte/src/Card.svelte
<script>
import { isEditingCard } from "../../shared/actions.js";
import { COLUMN_ORDER } from "../../shared/seed.js";
import { actions, board } from "./board.svelte.js";

let { columnId, card } = $props();
let columnIndex = $derived(COLUMN_ORDER.indexOf(columnId));
let isEditing = $derived(isEditingCard(board, columnId, card.id));

function autofocus(node) {
  node.focus();
  node.select();
}

function handleEditKeydown(event) {
  if (event.key === "Enter") {
    event.preventDefault();
    actions.commitEdit();
  } else if (event.key === "Escape") {
    event.preventDefault();
    actions.cancelEdit();
  }
}
</script>

<article class="card">
  {#if isEditing}
    <input
      {@attach autofocus}
      bind:value={board.editing.draftTitle}
      aria-label="Edit card title"
      onblur={actions.commitEdit}
      onkeydown={handleEditKeydown}
    />
  {:else}
    <button
      type="button"
      class="card-title card-title-button"
      onclick={() => actions.startEdit(columnId, card.id)}
    >
      {card.title}
    </button>
  {/if}

  <div class="card-actions">
    <button
      type="button"
      disabled={columnIndex === 0}
      onclick={() => actions.moveCard(columnId, card.id, "left")}
    >
      Left
    </button>
    <button
      type="button"
      disabled={columnIndex === COLUMN_ORDER.length - 1}
      onclick={() => actions.moveCard(columnId, card.id, "right")}
    >
      Right
    </button>
    <button type="button" onclick={() => actions.deleteCard(columnId, card.id)}>
      Delete
    </button>
  </div>
</article>

// 07-solid/src/Card.jsx
import { Show, onMount } from "solid-js";

import { isEditingCard } from "../../shared/actions.js";
import { COLUMN_ORDER } from "../../shared/seed.js";

export function Card(props) {
  const columnIndex = () => COLUMN_ORDER.indexOf(props.columnId);
  const isEditing = () => isEditingCard(props.board, props.columnId, props.card.id);

  return (
    <article class="card">
      <Show
        when={isEditing()}
        fallback={
          <button
            type="button"
            class="card-title card-title-button"
            onClick={() => props.actions.startEdit(props.columnId, props.card.id)}
          >
            {props.card.title}
          </button>
        }
      >
        <EditInput
          value={props.board.editing.draftTitle}
          onInput={props.actions.updateDraft}
          onCommit={props.actions.commitEdit}
          onCancel={props.actions.cancelEdit}
        />
      </Show>

      <div class="card-actions">
        <button
          type="button"
          disabled={columnIndex() === 0}
          onClick={() => props.actions.moveCard(props.columnId, props.card.id, "left")}
        >
          Left
        </button>
        <button
          type="button"
          disabled={columnIndex() === COLUMN_ORDER.length - 1}
          onClick={() => props.actions.moveCard(props.columnId, props.card.id, "right")}
        >
          Right
        </button>
        <button
          type="button"
          onClick={() => props.actions.deleteCard(props.columnId, props.card.id)}
        >
          Delete
        </button>
      </div>
    </article>
  );
}

function EditInput(props) {
  let element;

  onMount(() => {
    element.focus();
    element.select();
  });

  function handleKeyDown(event) {
    if (event.key === "Enter") {
      event.preventDefault();
      props.onCommit();
    } else if (event.key === "Escape") {
      event.preventDefault();
      props.onCancel();
    }
  }

  return (
    <input
      ref={element}
      aria-label="Edit card title"
      value={props.value}
      onInput={(event) => props.onInput(event.currentTarget.value)}
      onBlur={() => props.onCommit()}
      onKeyDown={handleKeyDown}
    />
  );
}
